---
- hosts: prod-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker
  
  - name: stop and remove existing banking container
    command: sudo docker rm -f  mentorbank
    
  - name: deploy banking application
    command: sudo docker run -itd -p 8081:8081 --name mentorbank thtmounika/mentorbank:1
